"""
retrieval.py
------------
Text → scene retrieval using native CLIP 512-d embeddings.

Architecture fix (v2)
---------------------
Previously the text query was encoded as a 512-d CLIP vector, duplicated to
1024-d, then projected through PCA fitted on [image, BEV] pairs.  This caused
a fundamental modality gap: the PCA principal components do not align with
duplicated text vectors.

Now we use a weighted-average fused embedding space where every stored scene
vector is:
    fused = normalise(0.7 × img_embed + 0.3 × bev_embed)   (512-d)

Text queries use the CLIP text encoder natively into the same 512-d CLIP
embedding space that the *image* component dominates.  Since CLIP was trained
to align text with image features, this gives proper cosine similarity without
any projection hack.

A fine-tuned checkpoint (outputs/clip_finetuned.pt) is used if present.
"""

import json
import numpy as np
import torch
import clip
from pathlib import Path
from vector_store import VectorStore

EMBEDDINGS_DIR = Path("outputs/embeddings")
SCENES_DIR     = Path("data/kitti/scenes")
CKPT_PATH      = Path("outputs/clip_finetuned.pt")

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"


# ── Model loading ────────────────────────────────────────────────────────────

def load_model():
    """Load CLIP ViT-B/32, applying fine-tuned weights if available."""
    model, preprocess = clip.load("ViT-B/32", device=DEVICE)
    if CKPT_PATH.exists():
        state = torch.load(CKPT_PATH, map_location=DEVICE)
        model.load_state_dict(state)
        print("  [retrieval] Loaded fine-tuned checkpoint.")
    model.eval()
    return model, preprocess


# ── Text encoding (no PCA, no duplication) ──────────────────────────────────

def encode_text(query: str, model) -> np.ndarray:
    """
    Encode a natural-language query into the CLIP 512-d embedding space.
    Returns a normalised float32 vector ready for FAISS IndexFlatIP.
    """
    tokens = clip.tokenize([query], truncate=True).to(DEVICE)
    with torch.no_grad():
        feat = model.encode_text(tokens)
        feat = feat / feat.norm(dim=-1, keepdim=True)
    return feat.cpu().numpy().astype(np.float32)[0]


# ── Search ───────────────────────────────────────────────────────────────────

def search(query: str, k: int = 5):
    """Run a text query against the FAISS index and print results."""
    model, _ = load_model()
    store    = VectorStore.load()

    q_vec   = encode_text(query, model)
    results = store.search(q_vec, k=k)

    print(f"\nQuery: '{query}'")
    print(f"{'Rank':<5} {'Scene':<22} {'Score':<8}")
    print("-" * 37)
    for i, r in enumerate(results):
        print(f"{i+1:<5} {r['scene_id']:<22} {r['score']:.4f}")
    return results


# ── Evaluation ───────────────────────────────────────────────────────────────

def eval_recall(queries_and_expected: list[tuple], k: int = 5) -> float:
    """
    Compute Recall@k: fraction of queries where the expected scene is in top-k.
    queries_and_expected: list of (query_str, expected_scene_id)
    """
    model, _ = load_model()
    store    = VectorStore.load()

    hits = 0
    for query, expected_id in queries_and_expected:
        q_vec   = encode_text(query, model)
        results = store.search(q_vec, k=k)
        top_ids = [r["scene_id"] for r in results]
        if expected_id in top_ids:
            hits += 1

    recall = hits / len(queries_and_expected)
    print(f"\nRecall@{k}: {hits}/{len(queries_and_expected)} = {recall:.1%}")
    return recall


# ── Semantic batch evaluation (no exact ground truth needed) ─────────────────

def eval_semantic(k: int = 5) -> float:
    """
    Load ground-truth eval pairs from outputs/eval_pairs.json if available,
    otherwise fall back to a small hard-coded set.
    The eval_pairs.json is generated by generate_eval_pairs.py.
    """
    eval_path = Path("outputs/eval_pairs.json")
    if eval_path.exists():
        with open(eval_path) as f:
            pairs = json.load(f)
        print(f"  Loaded {len(pairs)} eval pairs from {eval_path}")
    else:
        # Minimal fallback – only use if eval_pairs.json not yet generated
        pairs = [
            {"query": "a road with multiple cars",             "scene_id": "scene_000001"},
            {"query": "urban driving scene with vehicles",     "scene_id": "scene_000010"},
            {"query": "street with cars and pedestrians",      "scene_id": "scene_000020"},
            {"query": "busy city intersection",                "scene_id": "scene_000050"},
            {"query": "driving on road with other vehicles",   "scene_id": "scene_000100"},
        ]
        print(f"  Warning: using {len(pairs)} hard-coded fallback eval pairs.")
        print(f"  Run: python src/generate_eval_pairs.py   to build a proper eval set.")

    qe = [(p["query"], p["scene_id"]) for p in pairs]
    return eval_recall(qe, k=k)


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    demo_queries = [
        "a road with cars parked on the side",
        "empty street with no vehicles",
        "intersection with multiple cars",
        "pedestrians walking near the road",
        "a car driving closely in front",
        "open highway with few objects",
        "urban street scene with traffic",
        "residential area with parked cars",
        "road with a cyclist nearby",
        "driving in heavy city traffic",
    ]
    for q in demo_queries:
        search(q, k=3)

    print("\n" + "=" * 50)
    print("Semantic Recall@5 evaluation")
    print("=" * 50)
    eval_semantic(k=5)
